source 'https://rubygems.org/'

gem 'puma'
gem 'sinatra'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem "rack-timeout", require: "rack/timeout/base"
gem 'stackprof'

group :development do
  gem 'sinatra-contrib'
end

group :test do
  gem 'rspec'
end
